### ISSUE TITLE
Api key

### ISSUE THREAD

**Issue by mdobson8** [bingbon-exchange/docs#3]
I cannot see anywhere within Bingbon to create an API key, is there something I have to do to see this?

**Comment by acdccollege** [comment]
you can find it after you login on https://bingbon.com/

**Comment by mdobson8** [comment]
Thanks, Do you have a direct link to the API management page? I cannot see the option once logged in, checked all menus

**Comment by acdccollege** [comment]
https://bingbon.com/account/api/

**Comment by dnanhkhoa** [comment]
Hi, I cannot use that link to access the API key. When I logged into my account and entered that link, it was then redirected to the homepage. Do I need to enable anything in my account to allow using this feature? I would like to use this feature to gather all of my trading records for statistics. Thank you in advance!

**Comment by mdobson8** [comment]
I have resolved this now, you have to contact BingBon on chat and ask for them to enable API access on your account.

**Comment by dnanhkhoa** [comment]
Thank you, I have contacted them to grant me an access.
