### ISSUE TITLE
Request Signing

### ISSUE THREAD

**Issue by mdobson8** [bingbon-exchange/docs#4]
I am having an issue signing requests, I get the message 'signature not match'. I have followed the documentation and my requests are as below;

Signing Request = 'POST/api/v1/user/getBalanceapiKey={apikeyhere}&currency=USDT&timestamp=1628221390627'

Endpoint Request = 'https://api-swap-rest.bingbon.pro/api/v1/user/getBalance?apiKey={apikeyhere}&currency=USDT&timestamp=1628221390627&sign={signaturehere}'

Can you advise if I am doing anything incorrect? Signing using the below code in c# which has always worked for me in Binance;

      public static string CreateSignature(string queryString, string secret)
      {

          byte[] keyBytes = Encoding.UTF8.GetBytes(secret);
          byte[] queryStringBytes = Encoding.UTF8.GetBytes(queryString);
          HMACSHA256 hmacsha256 = new HMACSHA256(keyBytes);

          byte[] bytes = hmacsha256.ComputeHash(queryStringBytes);

          return BitConverter.ToString(bytes).Replace("-", "").ToLower();
      }

**Comment by binbincai410** [comment]
- `bytes` also need to use base64 and urlencode encoding.
- You can refer to the following python code:
```
#coding: utf-8

# python3 mini_main.py
import urllib.request
import json
import base64
import hmac
import time

APIURL = "https://api-swap-rest.bingbon.pro"
APIKEY = ""
SECRETKEY = ""

def genSignature(path, method, paramsMap):
	sortedKeys = sorted(paramsMap)
	paramsStr = "&".join(["%s=%s" % (x, paramsMap[x]) for x in sortedKeys])
	paramsStr = method + path + paramsStr
	return hmac.new(SECRETKEY.encode("utf-8"), paramsStr.encode("utf-8"), digestmod="sha256").digest()

def post(url, body):
	print (url, body)
	req = urllib.request.Request(url, data=body.encode("utf-8"), headers={'User-Agent': 'Mozilla/5.0'})
	return urllib.request.urlopen(req).read()

def getBalance():
	paramsMap = {
		"apiKey": APIKEY,
		"timestamp": int(time.time()*1000),
		"currency": "USDT",
	}
	sortedKeys = sorted(paramsMap)
	paramsStr = "&".join(["%s=%s" % (x, paramsMap[x]) for x in sortedKeys])
	paramsStr += "&sign=" + urllib.parse.quote(base64.b64encode(genSignature("/api/v1/user/getBalance", "POST", paramsMap)))
	url = "%s/api/v1/user/getBalance" % APIURL
	return post(url, paramsStr)

def main():
	print(getBalance())

if __name__ == "__main__":
	main()
```
